module.exports = {
    events: {
        apiRequest: ["request"],
        apiRespond: ["request", "response"],
        channelCreate: ["channel"],
        channelDelete: ["channel"],
        channelPinsUpdate: ["channel", "time"],
        channelUpdate: ["oldChannel", "newChannel"],
        debug: ["info"],
        emojiCreate: ["emoji"],
        emojiDelete: ["emoji"],
        emojiUpdate: ["oldEmoji", "newEmoji"],
        error: ["error"],
        guildBanAdd: ["ban"],
        guildBanRemove: ["ban"],
        guildCreate: ["guild"],
        guildDelete: ["guild"],
        guildIntegrationsUpdate: ["guild"],
        guildMemberAdd: ["member"],
        guildMemberAvailable: ["member"],
        guildMemberRemove: ["member"],
        guildMembersChunk: ["members", "guild", "chunk"],
        guildMemberUpdate: ["oldMember", "newMember"],
        guildScheduledEventCreate: ["guildScheduledEvent"],
        guildScheduledEventDelete: ["guildScheduledEvent"],
        guildScheduledEventUpdate: ["oldGuildScheduledEvent", "newGuildScheduledEvent"],
        guildScheduledEventUserAdd: ["guildScheduledEvent", "user"],
        guildScheduledEventUserRemove: ["guildScheduledEvent", "user"],
        guildUnavailable: ["guild"],
        guildUpdate: ["oldGuild", "newGuild"],
        interactionCreate: ["interaction"],
        invalidated: [],
        invalidRequestWarning: ["invalidRequestWarningData"],
        inviteCreate: ["invite"],
        inviteDelete: ["invite"],
        messageCreate: ["message"],
        messageDelete: ["message"],
        messageDeleteBulk: ["messages"],
        messageReactionAdd: ["messageReaction", "user"],
        messageReactionRemove: ["messageReaction", "user"],
        messageReactionRemoveAll: ["message", "reactions"],
        messageReactionRemoveEmoji: ["reaction"],
        messageUpdate: ["oldMessage", "newMessage"],
        presenceUpdate: ["oldPresence", "newPresence"],
        rateLimit: ["rateLimitData"],
        ready: ["client"],
        roleCreate: ["role"],
        roleDelete: ["role"],
        roleUpdate: ["oldRole", "newRole"],
        shardDisconnect: ["event", "id"],
        shardError: ["error", "shardId"],
        shardReady: ["id", "unavailableGuilds"],
        shardReconnecting: ["id"],
        shardResume: ["id", "replayedEvents"],
        stageInstanceCreate: ["stageInstance"],
        stageInstanceDelete: ["stageInstance"],
        stageInstanceUpdate: ["oldStageInstance", "newStageInstance"],
        stickerCreate: ["sticker"],
        stickerDelete: ["sticker"],
        stickerUpdate: ["oldSticker", "newSticker"],
        threadCreate: ["thread"],
        threadDelete: ["thread"],
        threadListSync: ["threads"],
        threadMembersUpdate: ["oldMembers", "newMembers"],
        threadMemberUpdate: ["oldMember", "newMember"],
        threadUpdate: ["oldThread", "newThread"],
        typingStart: ["typing"],
        userUpdate: ["oldUser", "newUser"],
        voiceStateUpdate: ["oldState", "newState"],
        warn: ["info"],
        webhookUpdate: ["channel"],
    },
    template(params){
        return `module.exports = async (client${params}) => {
    //For extra information visit https://discord.js.org/#/docs/discord.js/stable/class/Client
    //Put your code below
};`
    },
}